# Generated by Django 6.0.6 on 2026-07-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_carpooloffer_carpoolseatbooking_taxiriderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
