# Generated by Django 6.0.6 on 2026-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_carbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolseatbooking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
