# Generated by Django 6.0.6 on 2026-07-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_carpoolseatbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='vehicle_type',
            field=models.CharField(default='car', max_length=20),
        ),
    ]
