# Generated by Django 6.0.6 on 2026-07-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_carpooloffer_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiriderequest',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
