# Generated by Django 6.0.6 on 2026-07-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_taxiriderequest_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiriderequest',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxiriderequest',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
