# Generated by Django 6.0.6 on 2026-07-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='drop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='drop_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
