# Generated by Django 6.0.6 on 2026-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_carbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portal_type',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
