# Generated by Django 6.0.6 on 2026-07-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_userprofile_portal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
