# Generated by Django 6.0.6 on 2026-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_carpooloffer_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
