# Generated by Django 6.0.6 on 2026-07-21 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_carpooloffer_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carpooloffer',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='carpooloffer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portal_type',
        ),
        migrations.CreateModel(
            name='RemovedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=150, unique=True)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('out_of_service', 'Out of Service'), ('sold', 'Sold / Decommissioned'), ('maintenance', 'Under Maintenance'), ('other', 'Other')], default='out_of_service', max_length=30)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
