# Generated by Django 6.0.6 on 2026-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_add_removed_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20),
        ),
    ]
