# Generated by Django 6.0.6 on 2026-07-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_carpooloffer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpooloffer',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
