# Generated by Django 6.0.6 on 2026-07-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_carpooloffer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portal_role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
